In [1]:
import pennylane as qml
import torch
import numpy as np

In [2]:
import time

In [3]:
#qpu = qml.device('qiskit.ibmq', wires=2, backend='ibmq_essex',shots=100)
#qpu = qml.device('qiskit.ibmq', wires=2, backend='ibmq_london',shots=100)
#qpu = qml.device('qiskit.ibmq', wires=2, backend='ibmq_vigo',shots=100)
qpu = qml.device('qiskit.aer', wires=2)

In [4]:
@qml.qnode(qpu,interface='torch')
def circuit(params,inputs=None):
    #qml.BasisState(np.asarray([0,0]),wires=[0,1])
    qml.RX(inputs[0],wires=0)
    qml.RZ(inputs[0],wires=0)
    qml.RX(params[0],wires=0)
    qml.RZ(params[0],wires=0)
    return qml.expval(qml.PauliZ(0))

In [5]:
from torch.nn.parameter import Parameter

In [6]:
class QCircuitNet(torch.nn.Module):
    def __init__(self):
        super(QCircuitNet, self).__init__()
        self.params=Parameter(torch.zeros(2,dtype=torch.float32))
        
    def forward(self,args):
        return circuit(self.params,inputs=args)

In [7]:
model=QCircuitNet()

In [8]:
for p in model.named_parameters():
    print(p)

('params', Parameter containing:
tensor([0., 0.], requires_grad=True))


In [9]:
target=-1

In [10]:
def cost(value,target):
    return torch.abs(value-target)**2

In [11]:
opt=torch.optim.Adam(model.parameters(),lr=0.1)

In [12]:
args=torch.zeros(2)

In [13]:
print(args.grad)

None


In [14]:
value=model(args)

This was 1 4.4s job

In [15]:
print(args.grad)

None


In [16]:
value.requires_grad

True

In [17]:
loss=cost(value,target)

In [18]:
print(model.params.grad)

None


In [19]:
loss.backward()

This took 4 jobs 4.5s each

In [20]:
qml.__version__

'0.6.1'

In [26]:
print(model.params.grad)

tensor([0.0273, 0.0000])


In [27]:
print(args.grad)

None


In [14]:
for i in range(200):
    print(time.strftime("%Y%m%d_%H%M%S"))
    for p in model.named_parameters():
        print(p)
    opt.zero_grad()
    value=model(args)
    loss=cost(value,target)
    loss.backward()
    opt.step()

20191113_123107
('params', Parameter containing:
tensor([0., 0.], requires_grad=True))
20191113_123108
('params', Parameter containing:
tensor([-0.1000,  0.0000], requires_grad=True))
20191113_123108
('params', Parameter containing:
tensor([-0.1883,  0.0000], requires_grad=True))
20191113_123108
('params', Parameter containing:
tensor([-0.2754,  0.0000], requires_grad=True))
20191113_123108
('params', Parameter containing:
tensor([-0.3661,  0.0000], requires_grad=True))
20191113_123108
('params', Parameter containing:
tensor([-0.4568,  0.0000], requires_grad=True))
20191113_123108
('params', Parameter containing:
tensor([-0.5503,  0.0000], requires_grad=True))
20191113_123109
('params', Parameter containing:
tensor([-0.6459,  0.0000], requires_grad=True))
20191113_123109
('params', Parameter containing:
tensor([-0.7432,  0.0000], requires_grad=True))
20191113_123109
('params', Parameter containing:
tensor([-0.8425,  0.0000], requires_grad=True))
20191113_123109
('params', Parameter con

20191113_123122
('params', Parameter containing:
tensor([-3.2878,  0.0000], requires_grad=True))
20191113_123122
('params', Parameter containing:
tensor([-3.2878,  0.0000], requires_grad=True))
20191113_123122
('params', Parameter containing:
tensor([-3.2877,  0.0000], requires_grad=True))
20191113_123122
('params', Parameter containing:
tensor([-3.2876,  0.0000], requires_grad=True))
20191113_123122
('params', Parameter containing:
tensor([-3.2874,  0.0000], requires_grad=True))
20191113_123123
('params', Parameter containing:
tensor([-3.2872,  0.0000], requires_grad=True))
20191113_123123
('params', Parameter containing:
tensor([-3.2870,  0.0000], requires_grad=True))
20191113_123123
('params', Parameter containing:
tensor([-3.2868,  0.0000], requires_grad=True))
20191113_123123
('params', Parameter containing:
tensor([-3.2866,  0.0000], requires_grad=True))
20191113_123123
('params', Parameter containing:
tensor([-3.2863,  0.0000], requires_grad=True))
20191113_123123
('params', Par

20191113_123136
('params', Parameter containing:
tensor([-3.2621,  0.0000], requires_grad=True))
20191113_123137
('params', Parameter containing:
tensor([-3.2618,  0.0000], requires_grad=True))
20191113_123137
('params', Parameter containing:
tensor([-3.2615,  0.0000], requires_grad=True))
20191113_123137
('params', Parameter containing:
tensor([-3.2612,  0.0000], requires_grad=True))
20191113_123137
('params', Parameter containing:
tensor([-3.2609,  0.0000], requires_grad=True))
20191113_123137
('params', Parameter containing:
tensor([-3.2606,  0.0000], requires_grad=True))
20191113_123137
('params', Parameter containing:
tensor([-3.2603,  0.0000], requires_grad=True))
20191113_123138
('params', Parameter containing:
tensor([-3.2600,  0.0000], requires_grad=True))
20191113_123138
('params', Parameter containing:
tensor([-3.2596,  0.0000], requires_grad=True))
20191113_123138
('params', Parameter containing:
tensor([-3.2593,  0.0000], requires_grad=True))
20191113_123138
('params', Par